apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-datagen
  name: ksql-datagen
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-datagen
    spec:
      containers:
      - args:
        - bash
        - -c
        - echo Waiting for Kafka to be ready... && cub kafka-ready -b broker:9092
          1 40 && echo Waiting for Confluent Schema Registry to be ready... && cub
          sr-ready schema-registry 8081 40 && echo Waiting a few seconds for topic
          creation to finish... && sleep 11 && cp /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.0.0.jar
          /usr/share/java/ksql-examples/monitoring-interceptors-5.0.0.jar && tail
          -f /dev/null
        env:
        - name: KSQL_CONFIG_DIR
          value: /etc/ksql
        - name: KSQL_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties
        - name: STREAMS_BOOTSTRAP_SERVERS
          value: broker:9092
        - name: STREAMS_SCHEMA_REGISTRY_HOST
          value: schema-registry
        - name: STREAMS_SCHEMA_REGISTRY_PORT
          value: "8081"
        image: confluentinc/ksql-examples:5.0.0
        name: ksql-datagen
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/java/monitoring-interceptors/
          name: komp-mi2
      restartPolicy: Always
      volumes:
      - name: komp-mi2
        persistentVolumeClaim:
          claimName: komp-mi2
status: {}
