apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-cli
  name: ksql-cli
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-cli
    spec:
      containers:
      - command:
        - /bin/sh
        image: confluentinc/cp-ksql-cli:5.0.0
        name: ksql-cli
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
